### ISSUE TITLE
Problema com máscara de CPF

### ISSUE THREAD

**Issue by diogocs1** [ntiufalara/universidade-digital#2]
Problema com a máscara de CPF ao alterar os usuários que tem como nome de usuário um nome qualquer. Não permite salvar.

![captura](https://s4.postimg.org/6tpygcb4d/Captura_de_tela_de_2017_02_20_13_14_09.png)

**Comment by Cloves23** [comment]
Corrigido, agora o campo não possui mais máscara e aceita outros dados que não seja um CPF. Ele também só irá validar o usuário pelo CPF se seguir o padrão numérico dele, ou seja, quando forem nos formatos "xxx.xxx.xxx-yy" ou xxxxxxxxxyy".
